# Generated by Django 5.2.16 on 2026-08-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, editable=False, help_text="Incremented to invalidate every outstanding token for this account. Access tokens carry the value they were minted with as the 'jtv' claim; a mismatch rejects the token.", verbose_name='token version'),
        ),
    ]
