# Generated by Django 5.2.16 on 2026-08-10 09:06

import django.db.models.deletion
import django.db.models.functions.text
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='Display name of the institution.', max_length=200, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-safe identifier, typically the subdomain label. Also seeds the schema name when one is not given explicitly.', max_length=63, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to suspend the tenant. The schema and its data are kept, but requests for its domains are refused.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ('name', 'created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('schema_name__regex', '^[a-z][a-z0-9_]{0,62}$')), name='tenant_schema_name_is_bare_identifier', violation_error_message='Schema names must be bare lower-case SQL identifiers.')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ('domain',),
                'constraints': [models.CheckConstraint(condition=models.Q(('domain', django.db.models.functions.text.Lower('domain'))), name='domain_is_lowercase', violation_error_message='Domains must be stored lower-cased.')],
            },
        ),
    ]
