# Generated by Django 5.2.16 on 2026-08-16 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=64, verbose_name='device ID')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='device name')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'device session',
                'verbose_name_plural': 'device sessions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('successful', models.BooleanField(db_index=True, default=False, verbose_name='successful')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('failure_reason', models.CharField(blank=True, max_length=64, verbose_name='failure reason')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'login attempt',
                'verbose_name_plural': 'login attempts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('password_hash', models.CharField(max_length=128, verbose_name='password hash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'password history entry',
                'verbose_name_plural': 'password history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TokenFamily',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revocation_reason', models.CharField(blank=True, choices=[('logout', 'User logged out'), ('logout_all', 'User logged out of all devices'), ('password_changed', 'Password changed'), ('reuse_detected', 'Refresh token reuse detected'), ('admin_revoked', 'Revoked by an administrator'), ('user_deactivated', 'Account deactivated'), ('tenant_suspended', 'Tenant suspended'), ('session_cap', 'Session limit exceeded'), ('key_rotated', 'Signing key retired')], max_length=32, verbose_name='revocation reason')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_families', to='authentication.devicesession', verbose_name='device session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_families', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'token family',
                'verbose_name_plural': 'token families',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token hash')),
                ('jti', models.UUIDField(editable=False, unique=True, verbose_name='JWT ID')),
                ('generation', models.PositiveIntegerField(default=1, verbose_name='generation')),
                ('status', models.CharField(choices=[('active', 'Active'), ('rotated', 'Rotated'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('compromised', 'Compromised')], db_index=True, default='active', max_length=16, verbose_name='status')),
                ('revocation_reason', models.CharField(blank=True, choices=[('logout', 'User logged out'), ('logout_all', 'User logged out of all devices'), ('password_changed', 'Password changed'), ('reuse_detected', 'Refresh token reuse detected'), ('admin_revoked', 'Revoked by an administrator'), ('user_deactivated', 'Account deactivated'), ('tenant_suspended', 'Tenant suspended'), ('session_cap', 'Session limit exceeded'), ('key_rotated', 'Signing key retired')], max_length=32, verbose_name='revocation reason')),
                ('issued_at', models.DateTimeField(verbose_name='issued at')),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='rotated at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='authentication.refreshtoken', verbose_name='replaced by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='authentication.devicesession', verbose_name='device session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='authentication.tokenfamily', verbose_name='family')),
            ],
            options={
                'verbose_name': 'refresh token',
                'verbose_name_plural': 'refresh tokens',
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='AuthAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_type', models.CharField(choices=[('login_succeeded', 'Login succeeded'), ('login_failed', 'Login failed'), ('account_locked', 'Account locked'), ('token_refreshed', 'Token refreshed'), ('refresh_unknown', 'Unknown refresh token presented'), ('refresh_reuse_detected', 'Refresh reuse detected'), ('cross_tenant_token_rejected', 'Cross-tenant token rejected'), ('logout', 'Logout'), ('logout_all', 'Logout all devices'), ('force_logout', 'Forced logout'), ('password_changed', 'Password changed'), ('tenant_suspended', 'Tenant suspended'), ('key_rotated', 'Signing key rotated')], db_index=True, max_length=48, verbose_name='event type')),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('notice', 'Notice'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=16, verbose_name='severity')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='detail')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events_performed', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'authentication event',
                'verbose_name_plural': 'authentication events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='authevent_type_recent_idx'), models.Index(fields=['user', '-created_at'], name='authevent_user_recent_idx'), models.Index(condition=models.Q(('severity__in', ('warning', 'critical'))), fields=['-created_at'], name='authevent_critical_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(condition=models.Q(('ended_at__isnull', True)), fields=['user', '-created_at'], name='devsession_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(condition=models.Q(('successful', False)), fields=['email', '-created_at'], name='loginattempt_email_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', '-created_at'], name='loginattempt_ip_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', '-created_at'], name='pwdhistory_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenfamily',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user'], name='tokenfamily_user_live_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['family', 'generation'], name='reftoken_lineage_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['user', 'status'], name='reftoken_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='reftoken_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='reftoken_generation_positive'),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='reftoken_expiry_after_issue'),
        ),
    ]
